/**
 * Miscellaneous Icons Registry
 *
 * @module icons/registry/misc
 */

import {
  Sparkles,
  Zap,
  Gift,
  Award,
  Crown,
  Medal,
  Trophy,
  Target,
  Flag,
  Bookmark,
  Tag,
  Hash,
  Globe,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Lightbulb,
  Rocket,
  Package,
  Box,
  Layers,
  Grid,
  List,
  LayoutGrid,
  LayoutList,
  Code,
  Terminal,
  Database,
  Server,
  Cloud,
  Cpu,
  Palette,
  Briefcase,
  GraduationCap,
  Bot,
  Building2,
  Github,
  Linkedin,
} from 'lucide-react';

export const miscIcons = {
  sparkles: Sparkles,
  magic: Sparkles,
  zap: Zap,
  lightning: Zap,
  gift: Gift,
  award: Award,
  crown: Crown,
  medal: Medal,
  trophy: Trophy,
  target: Target,
  palette: Palette,
  briefcase: Briefcase,
  'graduation-cap': GraduationCap,
  flag: Flag,
  bookmark: Bookmark,
  tag: Tag,
  hash: Hash,
  hashtag: Hash,
  globe: Globe,
  world: Globe,
  lock: Lock,
  unlock: Unlock,
  eye: Eye,
  view: Eye,
  'eye-off': EyeOff,
  hide: EyeOff,
  lightbulb: Lightbulb,
  idea: Lightbulb,
  rocket: Rocket,
  package: Package,
  box: Box,
  layers: Layers,
  grid: Grid,
  list: List,
  'layout-grid': LayoutGrid,
  'layout-list': LayoutList,
  code: Code,
  terminal: Terminal,
  database: Database,
  server: Server,
  cloud: Cloud,
  cpu: Cpu,
  bot: Bot,
  'building-2': Building2,
  github: Github,
  linkedin: Linkedin,
} as const;
